-- SQLBook: Code


CREATE TABLE parent (
    id_parent INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);






CREATE TABLE user (
  id_user INT AUTO_INCREMENT PRIMARY KEY,
name  VARCHAR(50) NOT NULL,
 grade VARCHAR(50) NOT NULL,
 birthday DATE NOT NULL,
photo VARCHAR(255) NOT NULL
);



